use std::collections::HashMap;
use std::io::Write;
use std::path::Path;

use petgraph::graph::DiGraph;
use petgraph::graph::NodeIndex;

use super::PhpClass;

/// # Errors
/// Returns `std::io::Error` if the output file cannot be created or written.
pub fn generate(
    classes: &[PhpClass],
    output_path: &Path,
    max_classes: usize,
) -> std::io::Result<usize> {
    let sorted = topo_sort(classes);

    let limit = if max_classes > 0 {
        sorted.len().min(max_classes)
    } else {
        sorted.len()
    };

    let selected = &sorted[..limit];

    let mut file = std::fs::File::create(output_path)?;
    writeln!(file, "<?php")?;
    writeln!(file)?;
    writeln!(file, "// Generated by sfc preload")?;
    writeln!(file, "// {limit} classes")?;

    for &idx in selected {
        writeln!(file, "require_once '{}';", classes[idx].file_path.display())?;
    }

    Ok(limit)
}

fn topo_sort(classes: &[PhpClass]) -> Vec<usize> {
    let mut graph = DiGraph::<usize, ()>::new();
    let mut index_map: HashMap<&str, NodeIndex> = HashMap::new();

    let nodes: Vec<NodeIndex> = classes
        .iter()
        .enumerate()
        .map(|(i, cls)| {
            let node = graph.add_node(i);
            index_map.insert(cls.fqcn.as_str(), node);
            node
        })
        .collect();

    for (i, cls) in classes.iter().enumerate() {
        if let Some(ref parent) = cls.parent
            && let Some(&parent_node) = index_map.get(parent.as_str())
        {
            graph.add_edge(parent_node, nodes[i], ());
        }
        for iface in &cls.interfaces {
            if let Some(&iface_node) = index_map.get(iface.as_str()) {
                graph.add_edge(iface_node, nodes[i], ());
            }
        }
    }

    match petgraph::algo::toposort(&graph, None) {
        Ok(order) => order.into_iter().map(|n| graph[n]).collect(),
        Err(_) => (0..classes.len()).collect(),
    }
}

#[cfg(test)]
mod tests {
    use tempfile::TempDir;

    use super::*;

    fn make_class(fqcn: &str, file: &str, parent: Option<&str>, interfaces: Vec<&str>) -> PhpClass {
        PhpClass {
            fqcn: fqcn.to_owned(),
            file_path: file.into(),
            parent: parent.map(ToOwned::to_owned),
            interfaces: interfaces.into_iter().map(ToOwned::to_owned).collect(),
        }
    }

    #[test]
    fn topo_sort_parents_first() {
        let classes = vec![
            make_class("App\\Child", "/child.php", Some("App\\Base"), vec![]),
            make_class("App\\Base", "/base.php", None, vec![]),
        ];

        let sorted = topo_sort(&classes);
        let base_pos = sorted
            .iter()
            .position(|&i| classes[i].fqcn == "App\\Base")
            .unwrap();
        let child_pos = sorted
            .iter()
            .position(|&i| classes[i].fqcn == "App\\Child")
            .unwrap();
        assert!(base_pos < child_pos);
    }

    #[test]
    fn topo_sort_interfaces_first() {
        let classes = vec![
            make_class("App\\Impl", "/impl.php", None, vec!["App\\Iface"]),
            make_class("App\\Iface", "/iface.php", None, vec![]),
        ];

        let sorted = topo_sort(&classes);
        let iface_pos = sorted
            .iter()
            .position(|&i| classes[i].fqcn == "App\\Iface")
            .unwrap();
        let impl_pos = sorted
            .iter()
            .position(|&i| classes[i].fqcn == "App\\Impl")
            .unwrap();
        assert!(iface_pos < impl_pos);
    }

    #[test]
    fn generate_writes_preload_file() {
        let tmp = TempDir::new().unwrap();
        let output = tmp.path().join("preload.php");

        let classes = vec![
            make_class("App\\Base", "/base.php", None, vec![]),
            make_class("App\\Child", "/child.php", Some("App\\Base"), vec![]),
        ];

        let count = generate(&classes, &output, 0).unwrap();
        assert_eq!(count, 2);

        let content = std::fs::read_to_string(&output).unwrap();
        assert!(content.starts_with("<?php"));
        assert!(content.contains("require_once '/base.php'"));
        assert!(content.contains("require_once '/child.php'"));

        let base_pos = content.find("/base.php").unwrap();
        let child_pos = content.find("/child.php").unwrap();
        assert!(base_pos < child_pos);
    }

    #[test]
    fn max_classes_limits_output() {
        let tmp = TempDir::new().unwrap();
        let output = tmp.path().join("preload.php");

        let classes = vec![
            make_class("A", "/a.php", None, vec![]),
            make_class("B", "/b.php", None, vec![]),
            make_class("C", "/c.php", None, vec![]),
        ];

        let count = generate(&classes, &output, 2).unwrap();
        assert_eq!(count, 2);

        let content = std::fs::read_to_string(&output).unwrap();
        let require_count = content.matches("require_once").count();
        assert_eq!(require_count, 2);
    }

    #[test]
    fn external_parent_does_not_break_sort() {
        let classes = vec![
            make_class("App\\Foo", "/foo.php", Some("Vendor\\Base"), vec![]),
            make_class("App\\Bar", "/bar.php", None, vec![]),
        ];

        let sorted = topo_sort(&classes);
        assert_eq!(sorted.len(), 2);
    }
}
